lint-frontend:
	make -C hexlet-chat-server lint

install:
	npm ci

start-frontend:
	make -C hexlet-chat-server start

start-backend:
	npx start-server

deploy:
	git push heroku main

start:
	make start-backend

develop:
	make start-backend & make start-frontend

build:
	rm -rf hexlet-chat-server/build
	npm run build
